---

- name: Install pdftotext on macOS
  ansible.builtin.package:
    name: poppler
    state: present
  register: result
  failed_when:
    - '"already installed" not in result.msg'
    - '"installed" not in result.msg'
    - '"Package installed" not in result.msg'
    - result.msg != ""
  when: ansible_facts.os_family == "Darwin"