---

- name: Install awscli
  ansible.builtin.package:
    name: awscli
    state: present
  register: result
  failed_when: '"installed" not in result.msg and result.msg != ""'
  when: ansible_os_family == 'Darwin'

