---

- name: XFCE desktop environment
  block:
    - name: "Install xfce4-terminal"
      ansible.builtin.package:
        name: xfce4-terminal
        state: present
      become: true

    - name: "Ensure /usr/share/xfce4/terminal/colorschemes exists"
      ansible.builtin.file:
        path: "/usr/share/xfce4/terminal/colorschemes"
        state: directory
        recurse: true
      become: true

    - name: soft link gruvbox theme
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/gruvbox.theme"
        dest: "/usr/share/xfce4/terminal/colorschemes/gruvbox.theme"
        force: true
        state: link
      become: true

    - name: "Ensure {{ ansible_env.HOME }}/.config/xfce4/terminal exists"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/xfce4/terminal"
        state: directory
        recurse: true

    - name: soft link terminal
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/terminalrc"
        dest: "{{ ansible_env.HOME }}/.config/xfce4/terminal/terminalrc"
        force: true
        state: link
  when: desktop_environment == 'xfce'

- name: TODO
  block:
    - name: TODO
      ansible.builtin.debug:
        msg: "TODO"
  when: ansible_os_family != 'Archlinux'
