---

- name: XFCE desktop environment
  block:
    - name: "Ensure /usr/share/xfce4/terminal/colorschemes exists"
      ansible.builtin.file:
        path: "/usr/share/xfce4/terminal/colorschemes"
        state: directory
        recurse: true
      become: true

    - name: soft link gruvbox theme
      ansible.builtin.file:
        src: "{{ playbook_dir }}/files/gruvbox.theme"
        dest: "/usr/share/xfce4/terminal/colorschemes/gruvbox.theme"
        force: true
        state: link
      become: true
  when: desktop_environment == 'xfce'
