---

- name: Install Authy on Archlinux
  ansible.builtin.include_role:
    name: aur_install
  vars:
    aur_install_pkg: authy
  when: ansible_os_family == 'Archlinux'

- name: Install Authy on Debian
  community.general.snap:
    name: authy
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install Authy on MacOS
  ansible.builtin.package:
    name: authy
    state: present
  when: ansible_os_family == 'Darwin'
  register: result
  failed_when: '"already installed" not in result.msg and result.msg != ""'
